### ISSUE TITLE
7牛上如何配置？

### ISSUE THREAD

**Issue by partytimex** [Eary/bing#3]
按照你的個 config 設置，圖片傳不上去7牛。可以介紹下如何配置，和注意事項嗎？

**Comment by Eary** [comment]
我的`config.bak.php`只是我自己的配置文件備份，裡面的`AK(AccessKey)` 和 `SK(SecretKey)` 已經被我替換成星號了。如果您要使用，就請修改配置文件填上自己七牛上的`AK` 和 `SK`。

> 請記得先創建存儲空間

獲取 → https://portal.qiniu.com/user/key  

附: [ 安全使用密钥建议](http://kb.qiniu.com/53cy0s73) 

End.
